export const properties = [
  {
    image: "/assets/apartment-1.jpg",
    title: "Luxury Modern Apartment",
    location: "DHA Lahore",
    type: "Apartment",
    beds: 2,
    baths: 2,
    area: "1,250 sq ft",
    price: "Rs. 85,000",
    purpose: "For Rent",
  },
  {
    image: "/assets/apartment-2.jpg",
    title: "Elegant City Apartment",
    location: "Gulberg Lahore",
    type: "Apartment",
    beds: 3,
    baths: 2,
    area: "1,600 sq ft",
    price: "Rs. 110,000",
    purpose: "For Rent",
  },
  {
    image: "/assets/apartment-3.jpg",
    title: "Contemporary Family Home",
    location: "Bahria Town Lahore",
    type: "House",
    beds: 3,
    baths: 3,
    area: "1,900 sq ft",
    price: "Rs. 125,000",
    purpose: "For Rent",
  },
  {
    image: "/assets/apartment-4.jpg",
    title: "Premium Kitchen Apartment",
    location: "DHA Lahore",
    type: "Apartment",
    beds: 2,
    baths: 2,
    area: "1,300 sq ft",
    price: "Rs. 95,000",
    purpose: "For Rent",
  },
  {
    image: "/assets/apartment-5.jpg",
    title: "Luxury Executive Apartment",
    location: "Gulberg Lahore",
    type: "Apartment",
    beds: 3,
    baths: 3,
    area: "1,850 sq ft",
    price: "Rs. 135,000",
    purpose: "For Rent",
  },
];export const projects = [
  {
    title: "Bahria Town Lahore",
    description: "Modern residential communities, villas, apartments and commercial opportunities.",
    image: "/assets/apartment-3.jpg",
  },
  {
    title: "DHA Lahore",
    description: "Premium residential and commercial properties in prime Lahore locations.",
    image: "/assets/apartment-1.jpg",
  },
  {
    title: "Gulberg Lahore",
    description: "A central Lahore destination for luxury apartments and commercial properties.",
    image: "/assets/apartment-2.jpg",
  },
  {
    title: "Al Ghani Garden",
    description: "Explore residential opportunities and modern housing options.",
    image: "/assets/apartment-4.jpg",
  },
  {
    title: "Royal Swiss City",
    description: "Discover new investment and residential property opportunities.",
    image: "/assets/apartment-5.jpg",
  },
  {
    title: "Lahore Properties",
    description: "Find houses, apartments, plots and commercial properties across Lahore.",
    image: "/assets/apartment-1.jpg",
  },
];

